### ISSUE TITLE
Proposal: do not run the action job if no Asana URL in the PR description.

### ISSUE THREAD

**Issue by lkallas** [Asana/create-app-attachment-github-action#14]
I propose the action example to have a condition not to run the job if PR description does not contain Asana URL.

Adding a condition to job `if: contains(github.event.pull_request.body, 'https://app.asana.com')`

```yaml
on:
  pull_request:
    types: [opened, reopened]

jobs:
  create-asana-attachment-job:
    if: contains(github.event.pull_request.body, 'https://app.asana.com') # Run job only if Asana link in the PR-s description
    runs-on: ubuntu-latest
    name: Create pull request attachments on Asana tasks
    steps:
      - name: Create pull request attachments
        uses: Asana/create-app-attachment-github-action@latest
        id: postAttachment
        with:
          asana-secret: ${{ secrets.ASANA_SECRET }}
      - name: Log output status
        run: echo "Status is ${{ steps.postAttachment.outputs.status }}"
```  

This way the action does not run if there's no actual need and doesn't spend action runner minutes.
