### ISSUE TITLE
How to pass an Asana task ID through the branch name

### ISSUE THREAD

**Issue by DmitrySalnikov** [Asana/create-app-attachment-github-action#7]
I tried to take the task ID from the PR branch name, for that I parsed the name and updated the PR body in step 1, so step 2 should find a link to the task in the body. But it seems that it get the data as it was when the workflow was triggered.

Is there a possibility to reload the data and pass it to the second step, or any other solutions?

```yaml
on:
  pull_request:
    types: [opened]

jobs:
  create-asana-attachment-job:
    runs-on: ubuntu-latest
    name: Create pull request attachments on Asana tasks
    steps:
      - name: Create comment with the link to Asana taks
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          head-branch-regex: '\d{16}'
          body-template: https://app.asana.com/0/1201376205424374/%headbranch%
      - name: Create pull request attachments
        uses: Asana/create-app-attachment-github-action@latest
        id: postAttachment
        with:
          asana-secret: ${{ secrets.ASANA_SECRET }}
```

**Comment by muddy-alex** [comment]
We use this in our pipeline with success. Being able to simply submit a GID to this action would be super helpful!

Pipeline
```
      - name: Get Task GID
        id: get_task_gid
        shell: bash
        run: echo "ASANA_TASK_GID=$(echo "$GITHUB_HEAD_REF" | grep -Eo '\d{16}')" >> $GITHUB_OUTPUT
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}

      - uses: bcgov-nr/action-pr-description-add@v0.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add_markdown: |
            
            *Asana Task*
            https://app.asana.com/0/<WorkspaceId>/${{ steps.get_task_gid.outputs.ASANA_TASK_GID }}

      - name: Attach pull request to Asana task
        uses: Asana/create-app-attachment-github-action@latest
        with:
          asana-secret: ${{ secrets.ASANA_SECRET }}
```
